### ISSUE TITLE
[Solved]Problem importing from Photoscan .PLY

### ISSUE THREAD

**Issue by FDDdan** [leon196/PointCloudExporter#1]
I received this error (**FormatException: Input string was not in the correct format**) with any ply file except Simon2. I've managed to modify the SimpleImporter.cs script but I'm new with GitHub, so I'll post the part that I modified here.
I noticed that the "element vertex" array.Length returns 3 from Simon2, but 9 on my files and the Convert.IntTo32 needed to return 2 (on Simon2 is "Array.Length - 1"), so I added an int to subtract the Array.Length to always return 2. Now it works with all the ply tested by me.

Here is the part of the code, with the int subtractor added by me

`
else if (lineText.Contains ("element vertex")) {

									string[] array = lineText.Split (' ');
									if (array.Length > 0) {
										int subtractor = array.Length - 2;
										vertexCount = Convert.ToInt32 (array [array.Length - subtractor]);
										if (vertexCount > maximumVertex) {
											levelOfDetails = 1 + (int)Mathf.Floor (vertexCount / maximumVertex);
											vertexCount = maximumVertex;
										}
										data.vertexCount = vertexCount;
										data.vertices = new Vector3[vertexCount];
										data.normals = new Vector3[vertexCount];
										data.colors = new Color[vertexCount];
									}`

**Comment by leon196** [comment]
I've updated the code with your lines.
Thanks!

**Comment by contactsamie** [comment]
@FDDdan @leon196  not sure about this but is it possible to export from the pointcloud to ply .  if not ( or if so ) what other formats are possible exports? Thanks
